# Generated by Django 4.2.8 on 2024-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='is_mailed',
            field=models.BooleanField(default=False),
        ),
    ]
