# Generated by Django 4.2.8 on 2024-01-13 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_quotationrequest_is_mailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
