# Generated by Django 4.2.8 on 2024-01-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('pages', '0003_quotationrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
