# Generated by Django 4.2.8 on 2024-01-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_userexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexperience',
            old_name='stars',
            new_name='rating',
        ),
    ]
