# Generated by Django 4.2.8 on 2024-01-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_stars_userexperience_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='fullname',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
