# Generated by Django 4.2.8 on 2024-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_userexperience_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperience',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_experience_pics/'),
        ),
    ]
