# Generated by Django 5.0 on 2024-01-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_userexperience_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexperience',
            name='occupation',
        ),
    ]
